# Recipe categories
Recipe_Category = ['Appetizers & Snacks', 'Appetizers & Starters', 'Baking', 'Beverages', 'Breakfast & Brunch',
                   'Desserts', 'Desserts & Baking', 'Ethnic Cuisine', 'Main Courses', 'Main Dishes',
                   'Preserves & Canning', 'Sauces & Condiments', 'Seasonal', 'Seasonal & Holiday', 'Side Dishes',
                   'Special Diet', 'Special Diets', 'Techniques & Methods', 'World Cuisines']

# Ingredient categories
All_Ingredients = ['Asian', 'Asian Noodles', 'Baked Appetizers', 'Bar Cookies', 'Bean & Lentil',
                   'Beef', 'Breads & Baking', 'Breakfast Meats', 'Cheese Plates', 'Cheesecakes',
                   'Chicken', 'Christmas', 'Chunky Soups', 'Classic', 'Clear Soups', 'Coffee',
                   'Cold Cereals', 'Cold Seafood', 'Cold Soups', 'Compliant Meals', 'Cream Pies', 'Cream Soups',
                   'Croissant Based', 'Dips & Spreads', 'Drop Cookies', 'Dry Heat', 'East African', 'East Asian',
                   'Easter', 'Easter dishes', 'Egg Dishes', 'Emulsified Sauces', 'European', 'Fall Produce',
                   'Fat-Based', 'Fermentation', 'Fermented Foods', 'Finger Foods', 'Fish', 'French',
                   'Fresh Juices', 'Fried Appetizers', 'Fruit Based', 'Fruit Dishes', 'Fruit Jams', 'Fruit Pies',
                   'Game Meats', 'Grain Salads', 'Green Salads', 'Griddle Favorites', 'Grilled', 'Grilling & BBQ',
                   'Healthy Options', 'Hot Cereals', 'Hot Chocolate', 'Iced Drinks', 'Italian', 'Italian Pasta',
                   'Keto Desserts', 'Keto Mains', 'Keto Sides', 'Knife Skills', 'Lamb', 'Latin',
                   'Latin American', 'Layer Cakes', 'Lebanese', 'Legume Based', 'Main Dishes', 'Mains',
                   'Mediterranean', 'Mixed Seafood', 'Mixing Methods', 'Modern', 'Moist Heat',
                   'Molecular Gastronomy', 'Mother Sauces', 'New Year', 'North African', 'North American',
                   'Other Cakes', 'Other Grains', 'Other Noodles', 'Pan Sauces', 'Persian', 'Pickled Vegetables',
                   'Picnic & Outdoor', 'Plant-Based Proteins', 'Pork', 'Potatoes', 'Poultry', 'Protein Salads',
                   'Quick Breads', 'Rice', 'Roasted', 'Sauces & Dressings', 'Sautéed', 'Savory', 'Shellfish',
                   'Sides', 'Smoking & Curing', 'Smoothie Bowls', 'Smoothies', 'Snacks', 'South Asian',
                   'Southeast Asian', 'Special Cakes', 'Special Occasion', 'Specialty', 'Specialty Breads',
                   'Specialty Cookies', 'Specialty Preserves', 'Spice Blends', 'Spreads', 'Spring Produce', 'Steamed',
                   'Stuffed Items', 'Summer Produce', 'Sweet', 'Table Condiments', 'Tarts', 'Tea', 'Thanksgiving',
                   'Tofu & Tempeh', 'Tomato Based', 'Turkish', 'Vegan Specific', 'Vegetable Mains',
                   'Vegetable Platters', 'Vegetable Salads', 'Vegetarian Mains', 'Virgin Classics',
                   'Wellness Drinks', 'West African', 'Whole30 Sides', 'Winter Comfort', 'Yeast Breads',
                   'Yogurt Dishes']

categories = {'Breakfast & Brunch': ['Breakfast Meats', 'Classic', 'Cold Cereals', 'Croissant Based', 'Egg Dishes',
                                     'Fruit Dishes', 'Griddle Favorites', 'Healthy Options', 'Hot Cereals', 'Savory',
                                     'Smoothie Bowls', 'Sweet', 'Yogurt Dishes'],
              'Appetizers & Snacks': ['bisque', 'broth', 'chowder', 'coleslaw', 'green salad', 'guacamole', 'hummus',
                                      'nachos', 'pasta salad', 'pate', 'potato salad', 'salsa', 'soup', 'spring rolls',
                                      'tapas', 'wings'],
              'Main Dishes': ['Asian Noodles', 'Bean & Lentil', 'Beef', 'Chicken', 'Fish', 'Italian Pasta', 'Lamb',
                              'Mixed Seafood', 'Other Noodles', 'Pork', 'Shellfish', 'Tofu & Tempeh',
                              'Vegetable Mains'],
              'Side Dishes': ['Grilled', 'Other Grains', 'Potatoes', 'Rice', 'Roasted', 'Sautéed', 'Steamed'],
              'Desserts': ['Cheesecakes', 'Layer Cakes', 'Special Cakes', 'apple pie', 'bread pudding', 'brownies',
                           'chocolate chip cookies', 'cookie bars', 'cream pie', 'custard', 'frozen yogurt',
                           'fruit tart', 'ice cream', 'mousse', 'sorbet'],
              'Beverages': ['Classic', 'Coffee', 'Fresh Juices', 'Hot Chocolate', 'Iced Drinks', 'Modern', 'Smoothies',
                            'Special Occasion', 'Tea', 'Virgin Classics', 'Wellness Drinks'],
              'Ethnic Cuisine': ['beef bourguignon', 'biryani', 'coq au vin', 'curry', 'dal', 'dim sum', 'dolma',
                                 'dumplings', 'enchiladas', 'fajitas', 'falafel', 'fattoush', 'fried rice', 'hummus',
                                 'kebab', 'moussaka', 'osso buco', 'pad thai', 'pasta', 'pizza', 'ramen', 'ratatouille',
                                 'risotto', 'satay', 'shawarma', 'stir-fry', 'sushi', 'tabbouleh', 'tacos', 'tamales',
                                 'tandoori', 'tempura', 'teriyaki', 'tom yum'],
              'Special Diet': ['cauliflower rice', 'gluten-free bread', 'gluten-free pasta', 'keto bread',
                               'keto dessert', 'keto snack', 'paleo bread', 'paleo dessert', 'paleo snack',
                               'vegan cake', 'vegan chili', 'vegan pasta', 'vegetable curry', 'vegetable stir-fry',
                               'veggie burger', 'zucchini noodles'],
              'Baking': ['baguette', 'banana bread', 'croissant', 'danish', 'muffins', 'pie crust', 'puff pastry',
                         'quiche', 'rye bread', 'sourdough', 'tart shell', 'whole wheat', 'zucchini bread'],
              'Seasonal': ['Christmas', 'Easter dishes', 'Thanksgiving', 'apple dishes', 'asparagus dishes', 'barbecue',
                           'grilled dishes', 'holiday dishes', 'pumpkin dishes', 'spring salad', 'summer salads',
                           'winter soups'],
              'Appetizers & Starters': ['Baked Appetizers', 'Cheese Plates', 'Chunky Soups', 'Clear Soups',
                                        'Cold Seafood', 'Cold Soups', 'Cream Soups', 'Dips & Spreads', 'Finger Foods',
                                        'Fried Appetizers', 'Grain Salads', 'Green Salads', 'Protein Salads',
                                        'Stuffed Items', 'Vegetable Platters', 'Vegetable Salads'],
              'Main Courses': ['Asian Noodles', 'Beef', 'Fish', 'Game Meats', 'Italian Pasta', 'Lamb', 'Legume Based',
                               'Mixed Seafood', 'Plant-Based Proteins', 'Pork', 'Poultry', 'Shellfish',
                               'Vegetable Mains'],
              'Desserts & Baking': ['Bar Cookies', 'Cheesecakes', 'Cream Pies', 'Drop Cookies', 'Fruit Pies',
                                    'Layer Cakes', 'Other Cakes', 'Quick Breads', 'Specialty Breads',
                                    'Specialty Cookies', 'Tarts', 'Yeast Breads'],
              'World Cuisines': ['East African', 'East Asian', 'French', 'Italian', 'Latin American', 'Lebanese',
                                 'Mediterranean', 'North African', 'North American', 'Persian', 'South Asian',
                                 'Southeast Asian', 'Turkish', 'West African'],
              'Special Diets': ['Breads & Baking', 'Compliant Meals', 'Keto Desserts', 'Keto Mains', 'Keto Sides',
                                'Main Dishes', 'Mains', 'Sauces & Dressings', 'Sides', 'Snacks', 'Vegan Specific',
                                'Vegetarian Mains', 'Whole30 Sides'],
              'Seasonal & Holiday': ['Christmas', 'Easter', 'Fall Produce', 'Grilling & BBQ', 'New Year',
                                     'Picnic & Outdoor', 'Spring Produce', 'Summer Produce', 'Thanksgiving',
                                     'Winter Comfort'],
              'Preserves & Canning': ['Fermented Foods', 'Fruit Based', 'Fruit Jams', 'Pickled Vegetables', 'Specialty',
                                      'Specialty Preserves', 'Tomato Based'],
              'Sauces & Condiments': ['Asian', 'Emulsified Sauces', 'European', 'Latin', 'Mother Sauces', 'Pan Sauces',
                                      'Spice Blends', 'Spreads', 'Table Condiments'],
              'Techniques & Methods': ['Dry Heat', 'Fat-Based', 'Fermentation', 'Knife Skills', 'Mixing Methods',
                                       'Moist Heat', 'Molecular Gastronomy', 'Smoking & Curing']}

