All_Ingredients = ['Asian', 'Asian Noodles', 'Asian Noodles', 'Baked Appetizers', 'Bar Cookies', 'Bean & Lentil',
                   'Beef', 'Beef', 'Breads & Baking', 'Breakfast Meats', 'Cheese Plates', 'Cheesecakes', 'Cheesecakes',
                   'Chicken', 'Christmas', 'Christmas', 'Chunky Soups', 'Classic', 'Classic', 'Clear Soups', 'Coffee',
                   'Cold Cereals', 'Cold Seafood', 'Cold Soups', 'Compliant Meals', 'Cream Pies', 'Cream Soups',
                   'Croissant Based', 'Dips & Spreads', 'Drop Cookies', 'Dry Heat', 'East African', 'East Asian',
                   'Easter', 'Easter dishes', 'Egg Dishes', 'Emulsified Sauces', 'European', 'Fall Produce',
                   'Fat-Based', 'Fermentation', 'Fermented Foods', 'Finger Foods', 'Fish', 'Fish', 'French',
                   'Fresh Juices', 'Fried Appetizers', 'Fruit Based', 'Fruit Dishes', 'Fruit Jams', 'Fruit Pies',
                   'Game Meats', 'Grain Salads', 'Green Salads', 'Griddle Favorites', 'Grilled', 'Grilling & BBQ',
                   'Healthy Options', 'Hot Cereals', 'Hot Chocolate', 'Iced Drinks', 'Italian', 'Italian Pasta',
                   'Italian Pasta', 'Keto Desserts', 'Keto Mains', 'Keto Sides', 'Knife Skills', 'Lamb', 'Lamb',
                   'Latin', 'Latin American', 'Layer Cakes', 'Layer Cakes', 'Lebanese', 'Legume Based', 'Main Dishes',
                   'Mains', 'Mediterranean', 'Mixed Seafood', 'Mixed Seafood', 'Mixing Methods', 'Modern', 'Moist Heat',
                   'Molecular Gastronomy', 'Mother Sauces', 'New Year', 'North African', 'North American',
                   'Other Cakes', 'Other Grains', 'Other Noodles', 'Pan Sauces', 'Persian', 'Pickled Vegetables',
                   'Picnic & Outdoor', 'Plant-Based Proteins', 'Pork', 'Pork', 'Potatoes', 'Poultry', 'Protein Salads',
                   'Quick Breads', 'Rice', 'Roasted', 'Sauces & Dressings', 'Sautéed', 'Savory', 'Shellfish',
                   'Shellfish', 'Sides', 'Smoking & Curing', 'Smoothie Bowls', 'Smoothies', 'Snacks', 'South Asian',
                   'Southeast Asian', 'Special Cakes', 'Special Occasion', 'Specialty', 'Specialty Breads',
                   'Specialty Cookies', 'Specialty Preserves', 'Spice Blends', 'Spreads', 'Spring Produce', 'Steamed',
                   'Stuffed Items', 'Summer Produce', 'Sweet', 'Table Condiments', 'Tarts', 'Tea', 'Thanksgiving',
                   'Thanksgiving', 'Tofu & Tempeh', 'Tomato Based', 'Turkish', 'Vegan Specific', 'Vegetable Mains',
                   'Vegetable Mains', 'Vegetable Platters', 'Vegetable Salads', 'Vegetarian Mains', 'Virgin Classics',
                   'Wellness Drinks', 'West African', 'Whole30 Sides', 'Winter Comfort', 'Yeast Breads',
                   'Yogurt Dishes', 'apple dishes', 'apple pie', 'asparagus dishes', 'baguette', 'banana bread',
                   'barbecue', 'beef bourguignon', 'biryani', 'bisque', 'bread pudding', 'broth', 'brownies',
                   'cauliflower rice', 'chocolate chip cookies', 'chowder', 'coleslaw', 'cookie bars', 'coq au vin',
                   'cream pie', 'croissant', 'curry', 'custard', 'dal', 'danish', 'dim sum', 'dolma', 'dumplings',
                   'enchiladas', 'fajitas', 'falafel', 'fattoush', 'fried rice', 'frozen yogurt', 'fruit tart',
                   'gluten-free bread', 'gluten-free pasta', 'green salad', 'grilled dishes', 'guacamole',
                   'holiday dishes', 'hummus', 'hummus', 'ice cream', 'kebab', 'keto bread', 'keto dessert',
                   'keto snack', 'moussaka', 'mousse', 'muffins', 'nachos', 'osso buco', 'pad thai', 'paleo bread',
                   'paleo dessert', 'paleo snack', 'pasta', 'pasta salad', 'pate', 'pie crust', 'pizza', 'potato salad',
                   'puff pastry', 'pumpkin dishes', 'quiche', 'ramen', 'ratatouille', 'risotto', 'rye bread', 'salsa',
                   'satay', 'shawarma', 'sorbet', 'soup', 'sourdough', 'spring rolls', 'spring salad', 'stir-fry',
                   'summer salads', 'sushi', 'tabbouleh', 'tacos', 'tamales', 'tandoori', 'tapas', 'tart shell',
                   'tempura', 'teriyaki', 'tom yum', 'vegan cake', 'vegan chili', 'vegan pasta', 'vegetable curry',
                   'vegetable stir-fry', 'veggie burger', 'whole wheat', 'wings', 'winter soups', 'zucchini bread',
                   'zucchini noodles']

Recipe_Category = ['Appetizers & Snacks', 'Appetizers & Starters', 'Baking', 'Beverages', 'Breakfast & Brunch',
                   'Desserts', 'Desserts & Baking', 'Ethnic Cuisine', 'Main Courses', 'Main Dishes',
                   'Preserves & Canning', 'Sauces & Condiments', 'Seasonal', 'Seasonal & Holiday', 'Side Dishes',
                   'Special Diet', 'Special Diets', 'Techniques & Methods', 'World Cuisines']
